### ISSUE TITLE
protoc-gen-gripmock causes panic

### ISSUE THREAD

**Issue by leowmjw** [gunk/gunk#274]
Trying to use gripmock to as a generator but failed (stack trace below).  How do I go about debugging it? 

Alternatively, if gunk can output .proto; i can run it in a separate process, but did not see docs on how to export gunk to .proto (i only saw .proto to gunk).  Thanks!

Generator: https://github.com/tokopedia/gripmock

Config:
```
$ cat .gunkconfig
; generate go libs, with grpc plugins
[generate go]
	plugins=grpc

; generate swagger configs, writing files to .
[generate swagger]

; gRPC Gateway
[generate]
protoc=grpc-gateway
logtostderr=true

; gripmock gRPC Mock
[generate gripmock]
```

Error:
```
/Users/mleow/Library/Caches/gunk/protoc-v3.9.1 --version
protoc-gen-go
protoc-gen-swagger
/Users/mleow/Library/Caches/gunk/protoc-v3.9.1 --grpc-gateway_out=logtostderr=true:/Users/mleow/GOMOD/go-rest/sdk --descriptor_set_in=/dev/stdin all.proto
protoc-gen-gripmock
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf0 pc=0x152027d]

goroutine 1 [running]:
main.main1.func2(0xc000217f48)
	/Users/mleow/go/pkg/mod/github.com/gunk/gunk@v0.2.0/main.go:59 +0x74
panic(0x15b97e0, 0x1b1ce30)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2
github.com/gunk/gunk/generate.(*Generator).generatePlugin(0xc0000fe100, 0xc0002d0000, 0x1, 0x1, 0x0, 0xc0002ce060, 0x5, 0x5, 0x0, 0x0, ...)
	/Users/mleow/go/pkg/mod/github.com/gunk/gunk@v0.2.0/generate/generate.go:301 +0x43d
github.com/gunk/gunk/generate.(*Generator).GeneratePkg(0xc0000fe100, 0xc0002e80c0, 0x1e, 0xc00023a000, 0x4, 0x5, 0xc000314960, 0x2e, 0x0, 0x0)
	/Users/mleow/go/pkg/mod/github.com/gunk/gunk@v0.2.0/generate/generate.go:194 +0x2d5
github.com/gunk/gunk/generate.Run(0x0, 0x0, 0xc0000a9260, 0x1, 0x1, 0x8, 0x0)
	/Users/mleow/go/pkg/mod/github.com/gunk/gunk@v0.2.0/generate/generate.go:87 +0x517
main.main1(0x0)
	/Users/mleow/go/pkg/mod/github.com/gunk/gunk@v0.2.0/main.go:84 +0xa11
main.main()
	/Users/mleow/go/pkg/mod/github.com/gunk/gunk@v0.2.0/main.go:45 +0x22
make: *** [gunk] Error 2

```

**Comment by karelbilek** [comment]
I think I fixed that in a recent commit

**Comment by karelbilek** [comment]
Please reopen if it still applies
